# Generated by Django 6.0.6 on 2026-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [models.Case(models.When(importance='CRITICAL', then=models.Value(0)), models.When(importance='HIGH', then=models.Value(1)), models.When(importance='MEDIUM', then=models.Value(2)), models.When(importance='LOW', then=models.Value(3)), default=models.Value(4), output_field=models.IntegerField()), 'deadline']},
        ),
    ]
