# Generated by Django 6.0.6 on 2026-07-12 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_personal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'is_personal', 'is_completed'], name='idx_task_to_pers_comp'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_by', 'is_personal', 'is_completed'], name='idx_task_by_pers_comp'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline', 'is_completed'], name='idx_task_deadline_comp'),
        ),
    ]
