# Generated by Django 6.0.6 on 2026-07-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor'), ('STAFF', 'Personal'), ('PROGRAMMER', 'Programador')], db_index=True, default='STUDENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'),
        ),
    ]
