# Generated by Django 6.0.6 on 2026-06-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='schedule_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('COURSE', 'Curso')], default='PERSONAL', max_length=10),
        ),
    ]
