# Generated by Django 6.0.6 on 2026-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduleentry_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
