# Generated by Django 6.0.6 on 2026-07-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_habit_habitcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
