# Generated by Django 6.0.6 on 2026-07-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcompletion',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
